import numpy as np 
array1=np.array((1,2,3,4,5)) 
array2=np.array((6,7,8,9,10))
add_result=np.add(array1,array2) 
print('Addition Result:',add_result) 
subtraction_result=np.subtract(array1,array2)
print('Subtraction Result:',subtraction_result)
multiplication_result=np.multiply(array1 , array2) 
print('Multiplication Result:',multiplication_result)
division_result=np.divide(array1 , array2)          
print('Division Result:',division_result)
modulus_result=np.mod(array1 , array2)
print('Modulus Result:',modulus_result)
power_result=np.power(array1 , 2)
print('Power Result:',power_result)
sqrt_result=np.sqrt(array1)
print('Square Root Result:',sqrt_result)
log_result=np.log(array1)
print('Logarithm Result:',log_result)
exp_result=np.exp(array1)
print('Exponential Result:',exp_result)